#
# Convert binary file to C-array
# Original author: Chloe M.
# PUBLIC DOMAIN
#

import sys

GEN_MSG = \
"""
/*
 * Generated by OSMORA bin2arr
 */
"""

def to_arr(file):
    print(GEN_MSG, end="")
    print("static uint8_t arr[] = { ", end="")

    while block := file.read():
        for i in range(len(block)):
            if i > 0 and i < len(block):
                print(", ", end="")
            if i % 15 == 0:
                print("\n    ", end="")
            val = '0x{:02X}'.format(block[i])
            print(f"{val}", end="")

        print("\n};")

if len(sys.argv) < 2:
    print("usage: bin2arr <bin>")
    exit(1)

try:
    with open(sys.argv[1], "rb") as file:
        to_arr(file)
except FileNotFoundError:
    print(f"Could not open \"{sys.argv[1]}\"")
